=== freegear/socdb/Components/NCSeedBoard/TestPlatform/BusGen/bin/config/basic.dtd
<!ELEMENT BUS (Main, Master*, Slave*)>

<!ELEMENT Main (name, width, channel_connection, memory_map)>
    <!ELEMENT name (#PCDATA)>
        <!ATTLIST name masternum CDATA #REQUIRED
                       slavenum  CDATA #REQUIRED>
    <!ELEMENT width (buswidth, addresswidth)>
        <!ELEMENT buswidth (#PCDATA)>
        <!ELEMENT addresswidth (#PCDATA)>

    <!ELEMENT channel_connection (write_addr, write_data, write_resp, read_addr, read_data)>
        <!ELEMENT write_addr (#PCDATA)>
        <!ELEMENT write_data (#PCDATA)>
        <!ELEMENT write_resp (#PCDATA)>
        <!ELEMENT read_addr (#PCDATA)>
        <!ELEMENT read_data (#PCDATA)>

    <!ELEMENT memory_map (remap_enable, map0, map1)>
        <!ELEMENT remap_enable (#PCDATA)>
        <!ELEMENT map0 (slave*)>
        <!ELEMENT map1 (slave*)>
            <!ELEMENT slave (#PCDATA)>
                <!ATTLIST slave start_addr CDATA #REQUIRED
                                area_addr CDATA #REQUIRED
                                end_addr CDATA #REQUIRED>

<!ELEMENT Master (connect_slave, operate_write, portconfig, masterregisterslice)>
    <!ATTLIST Master name CDATA #REQUIRED
                     writeidwid CDATA #REQUIRED
                     readidwid CDATA #REQUIRED>

    <!ELEMENT connect_slave (conslave_name*) >
        <!ELEMENT conslave_name (#PCDATA)>

    <!ELEMENT operate_write (method, lock_access, write_issuing_cap, read_issuing_cap)>
        <!ELEMENT method (#PCDATA)>
        <!ELEMENT lock_access (#PCDATA) >
        <!ELEMENT write_issuing_cap (#PCDATA) >
        <!ELEMENT read_issuing_cap (#PCDATA) >

    <!ELEMENT portconfig (writechannel, readchannel)>
        <!ELEMENT writechannel (channel_enable, lock , cache , protect , wstrb)>
            <!ELEMENT channel_enable (#PCDATA) >
            <!ELEMENT lock (#PCDATA) >
            <!ELEMENT cache (#PCDATA) >
            <!ELEMENT protect (#PCDATA) >
            <!ELEMENT wstrb (#PCDATA) >

        <!ELEMENT readchannel (channel_enable, lock , cache , protect)>

    <!ELEMENT masterregisterslice (mastertosi, sitomi)>
        <!ELEMENT mastertosi (#PCDATA) >
            <!ATTLIST mastertosi rnum CDATA #REQUIRED
                                 mode CDATA #REQUIRED>
        <!ELEMENT sitomi (#PCDATA) >
            <!ATTLIST sitomi rnum CDATA #REQUIRED
                             mode CDATA #REQUIRED>





<!ELEMENT Slave (arbiter, operate_read, portconfig, slaveregisterslice)>
    <!ATTLIST Slave name CDATA #REQUIRED>

    <!ELEMENT arbiter (method, priority)>
        <!ELEMENT priority (mastername*)>
            <!ELEMENT mastername (#PCDATA)>

    <!ELEMENT operate_read (write_issuing_cap, read_issuing_cap, burst_type)>
        <!ELEMENT burst_type (FIXED, INCR, WRAP)>
            <!ELEMENT FIXED (#PCDATA)>
            <!ELEMENT INCR (#PCDATA)>
            <!ELEMENT WRAP (#PCDATA)>

    <!ELEMENT slaveregisterslice (slavetomi, mitosi)>
        <!ELEMENT slavetomi (#PCDATA) >
            <!ATTLIST slavetomi rnum CDATA #REQUIRED
                                mode CDATA #REQUIRED>
        <!ELEMENT mitosi (#PCDATA) >
            <!ATTLIST mitosi rnum CDATA #REQUIRED
                             mode CDATA #REQUIRED>

=== freegear/socdb/Components/NCSeedBoard/TestPlatform/BusGen/bin/config/TEST_13_12/basic.xml
<?xml version="1.0"?>
<!DOCTYPE BUS SYSTEM "basic.dtd">
<!--?xml:stylesheet type="text/xsl" href="basic.xsl"?-->
<!-- Bus generation MAIN config file -->
<!-- Generator version 0.1           -->

<BUS>
<!-- __________________Main Setting AREA_________________________ -->


    <Main>
        <name masternum="13" slavenum="12">TEST_13_12</name>
        <width>
            <buswidth>32</buswidth>
            <addresswidth>32</addresswidth>
        </width>

        <channel_connection>
            <!-- cross_bar | shared_bus -->
            <write_addr>cross_bar</write_addr>
            <write_data>cross_bar</write_data>
            <write_resp>cross_bar</write_resp>
            <read_addr>cross_bar</read_addr>
            <read_data>cross_bar</read_data>
        </channel_connection>
    
        <memory_map>
            <remap_enable>disable</remap_enable>
            <map0>
                <slave start_addr="0x20100000" area_addr="0x20110000" end_addr="0x20110000">sram0</slave>
                <slave start_addr="0x20110000" area_addr="0x20220000" end_addr="0x20220000">sram1</slave>
                <slave start_addr="0x51200000" area_addr="0x51207000" end_addr="0x51207000">sram2</slave>
                <slave start_addr="0x51207000" area_addr="0x51209000" end_addr="0x51209000">sram3</slave>
                <slave start_addr="0x51217000" area_addr="0x51219000" end_addr="0x51219000">sram4</slave>
                <slave start_addr="0x51227000" area_addr="0x51229000" end_addr="0x51229000">sram5</slave>
                <slave start_addr="0x31207000" area_addr="0x31209000" end_addr="0x31209000">sram6</slave>
                <slave start_addr="0x85321000" area_addr="0x85324000" end_addr="0x85324000">sram7</slave>
                <slave start_addr="0x75321000" area_addr="0x75324000" end_addr="0x75324000">sram8</slave>
                <slave start_addr="0x75331000" area_addr="0x75334000" end_addr="0x75334000">sram9</slave>
                <slave start_addr="0x75341000" area_addr="0x75344000" end_addr="0x75344000">sram10</slave>
                <slave start_addr="0x75351000" area_addr="0x75354000" end_addr="0x75354000">sram11</slave>
            </map0>
            <!--Remap area "if you not use remap, 
                you need not fill this area"-->
            <map1>
                <slave start_addr="0x00000000" area_addr="0x0FFFFFFF" end_addr="0x0FFFFFFF">sram0</slave>
                <slave start_addr="0x10000000" area_addr="0x1FFFFFFF" end_addr="0x1FFFFFFF">sram1</slave>
                <slave start_addr="0x20000000" area_addr="0x2FFFFFFF" end_addr="0x2FFFFFFF">sram2</slave>
                <slave start_addr="0x30000000" area_addr="0x3FFFFFFF" end_addr="0x3FFFFFFF">sram3</slave>
                <slave start_addr="0x51217000" area_addr="0x51219000" end_addr="0x51219000">sram4</slave>
                <slave start_addr="0x51227000" area_addr="0x51229000" end_addr="0x51229000">sram5</slave>
                <slave start_addr="0x31207000" area_addr="0x31209000" end_addr="0x31209000">sram6</slave>
                <slave start_addr="0x85321000" area_addr="0x85324000" end_addr="0x85324000">sram7</slave>
                <slave start_addr="0x75321000" area_addr="0x75324000" end_addr="0x75324000">sram8</slave>
                <slave start_addr="0x75331000" area_addr="0x75334000" end_addr="0x75334000">sram9</slave>
                <slave start_addr="0x75341000" area_addr="0x75344000" end_addr="0x75344000">sram10</slave>
                <slave start_addr="0x75351000" area_addr="0x75354000" end_addr="0x75354000">sram11</slave>
            </map1>
        </memory_map>
    </Main>
    

<!-- __________________Master Setting AREA_________________________ -->

    <Master name="MASTER0" writeidwid="1" readidwid="1">
        <connect_slave>
            <!-- insert slave name -->
            <conslave_name>sram0</conslave_name> 
            <conslave_name>sram1</conslave_name> 
            <!-- <conslave_name>sram2</conslave_name> -->
            <conslave_name>sram3</conslave_name>
            <!-- <conslave_name>sram4</conslave_name> -->
            <conslave_name>sram11</conslave_name> 
            <conslave_name>sram5</conslave_name> 
            <conslave_name>sram6</conslave_name> 
            <!-- <conslave_name>sram7</conslave_name> -->
            <conslave_name>sram7</conslave_name> 
            <conslave_name>sram8</conslave_name> 
            <conslave_name>sram9</conslave_name> 
        </connect_slave>
        <operate_write>
            <!-- simple, advaneced -->
            <method>advanced</method>
            <!-- enable, disable-->
            <lock_access>enable</lock_access>
            <!-- max count number -->
            <write_issuing_cap>1</write_issuing_cap>
            <read_issuing_cap>1</read_issuing_cap>
        </operate_write>
        <portconfig>
            <writechannel>
                <channel_enable>enable</channel_enable>
                <lock>enable</lock>
                <cache>enable</cache>
                <protect>enable</protect>
                <wstrb>enable</wstrb>
            </writechannel>
            <readchannel>
                <channel_enable>enable</channel_enable>
                <lock>enable</lock>
                <cache>enable</cache>
                <protect>enable</protect>
            </readchannel>
        </portconfig>
        <masterregisterslice>
            <!-- mode = (FULL | FOWARD) rmum => total slice number -->
            <mastertosi rnum="3" mode="FULL">enable</mastertosi>
            <sitomi rnum="2" mode="FULL">enable</sitomi>
        </masterregisterslice>
    </Master>
    
    <Master name="MASTER1"  writeidwid="2" readidwid="1">
        <connect_slave>
            <!-- insert slave name -->
            <conslave_name>sram0</conslave_name>
            <!-- <conslave_name>sram1</conslave_name> -->
            <conslave_name>sram1</conslave_name>
            <!-- <conslave_name>sram3</conslave_name> -->
            <!-- <conslave_name>sram4</conslave_name> -->
            <conslave_name>sram5</conslave_name> 
            <conslave_name>sram7</conslave_name>
            <conslave_name>sram9</conslave_name> 
            <conslave_name>sram10</conslave_name> 
        </connect_slave>
        <operate_write>
            <!-- simple, advaneced -->
            <method>advanced</method>
            <!-- enable, disable-->
            <lock_access>enable</lock_access>
            <!-- max count number -->
            <write_issuing_cap>2</write_issuing_cap>
            <read_issuing_cap>4</read_issuing_cap>
        </operate_write>
        <portconfig>
            <writechannel>
                <channel_enable>enable</channel_enable>
                <lock>enable</lock>
                <cache>enable</cache>
                <protect>enable</protect>
                <wstrb>enable</wstrb>
            </writechannel>
            <readchannel>
                <channel_enable>enable</channel_enable>
                <lock>enable</lock>
                <cache>enable</cache>
                <protect>enable</protect>
            </readchannel>
        </portconfig>
        <masterregisterslice>
            <!-- mode = (FULL | FOWARD) rmum => total slice number -->
            <mastertosi rnum="2" mode="FULL">enable</mastertosi>
            <sitomi rnum="4" mode="FULL">enable</sitomi>
        </masterregisterslice>
    </Master>

    <Master name="MASTER2"  writeidwid="3" readidwid="7">
        <connect_slave>
            <!-- insert slave name -->
            <!-- <conslave_name>sram0</conslave_name> -->
            <!-- <conslave_name>sram1</conslave_name> -->
            <conslave_name>sram2</conslave_name> 
            <conslave_name>sram3</conslave_name>
            <conslave_name>sram4</conslave_name>
            <!-- <conslave_name>sram5</conslave_name> -->
            <conslave_name>sram6</conslave_name> 
            <conslave_name>sram7</conslave_name>
            <conslave_name>sram8</conslave_name> 
            <conslave_name>sram10</conslave_name> 
            <conslave_name>sram11</conslave_name> 
        </connect_slave>
        <operate_write>
            <!-- simple, advaneced -->
            <method>advanced</method>
            <!-- enable, disable-->
            <lock_access>enable</lock_access>
            <!-- max count number -->
            <write_issuing_cap>3</write_issuing_cap>
            <read_issuing_cap>3</read_issuing_cap>
        </operate_write>
        <portconfig>
            <writechannel>
                <channel_enable>enable</channel_enable>
                <lock>enable</lock>
                <cache>enable</cache>
                <protect>enable</protect>
                <wstrb>enable</wstrb>
            </writechannel>
            <readchannel>
                <channel_enable>enable</channel_enable>
                <lock>enable</lock>
                <cache>enable</cache>
                <protect>enable</protect>
            </readchannel>
        </portconfig>
        <masterregisterslice>
            <!-- mode = (FULL | FOWARD) rmum => total slice number -->
            <mastertosi rnum="1" mode="FULL">enable</mastertosi>
            <sitomi rnum="3" mode="FULL">enable</sitomi>
        </masterregisterslice>
    </Master>

    <Master name="MASTER3"  writeidwid="3" readidwid="3">
        <connect_slave>
            <!-- insert slave name -->
            <conslave_name>sram0</conslave_name> 
            <!-- <conslave_name>sram1</conslave_name> -->
            <!-- <conslave_name>sram2</conslave_name> -->
            <conslave_name>sram3</conslave_name> 
            <conslave_name>sram9</conslave_name> 
            <!-- <conslave_name>sram4</conslave_name> -->
            <!-- <conslave_name>sram5</conslave_name> -->
